### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VOCCTQ** [aluo-x/tensorflow_windows#5]
Hi -
can you build optimized TF build for Intel® Core™ i7-6770HQ with GPU CUDA 8, cuDNN 6.0 , AVX2, SSE4.2 and py 3.6.3?

For me it won't compile still breaks with:

`c:\users\[user]\desktop\tensorflow\tensorflow\core\kernels\eigen_spatial_convolutions.h(722): warning C4789: Der Puffer "" mit der Größe von 8 Bytes wird überlaufen; 32 Bytes werden ab Offset 0 geschrieben. [C:\Users\[user]\Desktop\tensorflow\tensorflow\co
ntrib\cmake\build\tf_core_kernels.vcxproj]
  cwise_op_arg.cc
c:\users\[user]\desktop\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\eigen\src\core\products\generalblockpanelkernel.h(1902): fatal error C1002: Im 2. Durchlauf ist kein Heapspeicher mehr für den Compiler verfügbar. [C:\Users\[user]\Des
ktop\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]
c:\users\[user]\desktop\tensorflow\tensorflow\contrib\cmake\build\external\eigen_archive\eigen\src\core\products\generalblockpanelkernel.h(1902): fatal error C1002: Im 2. Durchlauf ist kein Heapspeicher mehr für den Compiler verfügbar. [C:\Users\[user]\Des
ktop\tensorflow\tensorflow\contrib\cmake\build\tf_core_kernels.vcxproj]`

I would be nice if you can help me :)

best wishes

**Comment by aluo-x** [comment]
Yes, this should be possible. Potentially doable this week.
I was originally planning on waiting for tensorflow 1.5 or nvcc to get their bugs (see tensorflow issue 14691) fixed before attempting a CUDA 9 w/ AVX2 build.

**Comment by VOCCTQ** [comment]
That was a realy fast response!
It would be pretty cool if you do that. 
Do you also know something about my issue? Does 16GB ram not enought to compile tf?

I would also preffer tf 1.5 with cuda 9 - but wanted to give my system the first try to see how fast it will run on my GPU.

**Comment by aluo-x** [comment]
See the link in my previous answer. There seems to be a bug in CUDA 9 right now.

**Comment by aluo-x** [comment]
Seems like there was an error with AVX2 on VS 2015, trying again with AVX now.

**Comment by aluo-x** [comment]
Alright, took slightly over 3 hours to build. 
This is CUDA 8 + **cudnn 7**
Seems to work fine, let me know if there are any issues.

**Comment by VOCCTQ** [comment]
Awesome, it seems to be work just 1 warning left because of AVX2:
`2017-11-27 08:12:39.790425: I C:\optimae\tensorflow-1.4.0\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2017-11-27 08:12:40.258787: I C:\optimae\tensorflow-1.4.0\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:09:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2017-11-27 08:12:40.259037: I C:\optimae\tensorflow-1.4.0\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1)`

Do you know why AVX2 failed to compile or does it depends on the open issue?

**Comment by aluo-x** [comment]
This is issue 10199 from Tensorflow, and supposedly fixed in pull request 13525. However I have not seen this actually fixed for VS 2015. 

Regardless, this will stop being an issue very soon as we transition to CUDA 9 in the next release. Since AVX2 does work with VS2017. 

Regardless, the performance penalty I have seen from enabling AVX + GPU vs GPU only is very small, probably even smaller when you compare AVX2 + GPU vs AVX + GPU.

**Comment by VOCCTQ** [comment]
Okay, then I'll wait for CUDA 9 release to check the differences (speed).

And big thanks for doing the compile, it's really awesome :)

**Comment by colmantse** [comment]
hi, I see the tf-gpu wheel for py 3.6 is completed. one thing tho, I thought cudnn 7 is supported only by CUDA 9, how come it is compiled with cuda 8 and cudnn 7?
