### ISSUE TITLE
an error encountered when building tensorflow

### ISSUE THREAD

**Issue by argman** [aluo-x/tensorflow_windows#7]
have you see this when building tensorflow? I cannot find any workaround to repair this, and really frustrated

Building NVCC (Device) object CMakeFiles/tf_core_gpu_kernels.dir/__/__/core/kernels/Release/tf_core_gpu_kernels_generated_adjust_contrast_op_gpu.cu.cc.obj (任务 ID: 3973)
  nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified (任务 ID: 3973)
  CMake Error at tf_core_gpu_kernels_generated_adjust_contrast_op_gpu.cu.cc.obj.Release.cmake:222 (message): (任务 ID: 3973)
    Error generating F:/Develop (任务 ID: 3973)
    Tools/tensorflow-1.3.1/tensorflow/contrib/cmake/build/CMakeFiles/tf_core_gpu_kernels.dir/__/__/core/kernels/Release/tf_core_gpu_kernels_generated_adjust_contrast_op_gpu.cu.cc.obj (任务 ID: 3973)

**Comment by argman** [comment]
and if possible, can you kindly provide the tensorflow libs used in c++, not just the python wheels.

**Comment by aluo-x** [comment]
See this:
https://bitbucket.org/eigen/eigen/pull-requests/351/win-nvcc/diff
